import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import IdrWorkspace from '@site/src/components/IdrWorkspace';
import styles from './index.module.css';

const pdfUrl='https://fksmm.skunkworksacademy.com/idr/Fernanda_Koppe_Souto_Maior_Macias_IDR.pdf';
const startCards = [
  ['01','Review the roadmap','Confirm target roles, learning time, tool access and the first operational process.','/idr/overview'],
  ['02','Begin the 12-week sprint','Complete instructor-led learning, labs and evidence in the planned sequence.','/idr/12-week-sprint'],
  ['03','Build portfolio evidence','Develop five sanitised projects that translate learning into job-market proof.','/idr/portfolio'],
  ['04','Track goals and KPIs','Measure consistency, evidence quality, automation testing and career conversion.','/idr/kpis'],
  ['05','Use verified resources','Open current official Microsoft, IBM and Google learning sources.','/idr/resources'],
  ['06','Prepare mentor reviews','Use structured 30, 60 and 90-day gates with Raydo Matthee.','/idr/mentoring'],
];

function Hero(){return <header className={styles.hero}><div className={styles.heroGrid}><div><div className={styles.brandLine}><img src="/img/favicon-white.svg" alt=""/><span>Skunkworks Academy · Individual Development Roadmap</span></div><p className={styles.eyebrow}>12-month professional development workspace</p><h1>Welcome,<span> Fernanda.</span></h1><p className={styles.subtitle}>AI-Enabled Business Operations · Process Improvement · Strategic Executive Support</p><p className={styles.lead}>Build from an experienced executive-support and business-operations base toward measurable capability in analytics, workflow automation, process design, AI-enabled productivity and transformation leadership.</p><div className={styles.actions}><Link className="button button--primary button--lg" to="/idr/12-week-sprint">Start the sprint</Link><a className="button button--secondary button--lg" href={pdfUrl} download>Download PDF IDR</a><Link className="button button--secondary button--lg" to="/idr/calendar">Sync calendar</Link></div><p className={styles.privacy}><strong>Public repository boundary:</strong> use synthetic or expressly authorised information only. Do not enter executive, customer, financial, employee or confidential business data.</p></div><aside className={styles.summary} aria-label="Roadmap summary"><div><span>Provisional placement</span><strong>Business Operations & Digital Transformation Practitioner</strong></div><div><span>Mentor / reviewer</span><strong>Raydo Matthee</strong></div><div><span>Weekly commitment</span><strong>8–12 structured hours</strong></div><div><span>Formal review gates</span><strong>30 · 60 · 90 days</strong></div><div><span>Portfolio target</span><strong>5 applied projects</strong></div><div><span>North Star</span><strong>August 2027</strong></div></aside></div></header>}

export default function Home(){return <Layout title="Welcome Fernanda — Individual Development Roadmap" description="Fernanda Macias’s interactive AI-enabled business operations development roadmap."><Hero/><main className={styles.main}><section className={styles.notice}><strong>Confidential source, sanitised online view.</strong> This site exposes the learning plan, targets and execution framework. Personal contact details and private assessment responses are intentionally excluded.</section><section className={styles.section}><div className={styles.heading}><div><p className={styles.kicker}>Immediate action</p><h2>Start here</h2></div><span>Complete through evidence and mentor review</span></div><div className={styles.grid}>{startCards.map(([n,t,c,l])=><Link className={styles.card} to={l} key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p><strong>Open →</strong></Link>)}</div></section><section className={styles.northStar}><p className={styles.kicker}>12-month North Star</p><blockquote>By August 2027, Fernanda should be able to lead an AI-enabled business-operations improvement initiative, translate executive and operational needs into structured processes, produce decision-ready dashboards, configure a controlled workflow automation, and present a credible portfolio for senior executive-support, operations, project-coordination or business-transformation roles.</blockquote></section><section className={styles.stats}><div><strong>12</strong><span>weekly sprint modules</span></div><div><strong>10</strong><span>credential targets</span></div><div><strong>5</strong><span>portfolio projects</span></div><div><strong>7</strong><span>development goals</span></div></section><section id="workspace" className={styles.workspace}><IdrWorkspace/></section></main></Layout>}
