import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();const errors=[];const required=['docusaurus.config.js','sidebars.js','src/pages/index.jsx','src/components/IdrWorkspace/index.jsx','docs/overview.md','docs/12-week-sprint.md','docs/portfolio.md','docs/resources.md','static/CNAME','static/img/favicon-black.svg','static/img/favicon-white.svg','idr/Fernanda_Koppe_Souto_Maior_Macias_IDR.pdf','static/downloads/fernanda-idr-12-week-calendar.ics','.github/workflows/deploy-pages.yml'];
for(const f of required){const p=path.join(root,f);if(!fs.existsSync(p)||fs.statSync(p).size===0)errors.push(`${f}: missing or empty`)}
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const checks=[['docusaurus.config.js',"url: siteUrl",'custom domain URL'],['docusaurus.config.js',"baseUrl: '/'",'root base URL'],['docusaurus.config.js','favicon-black.svg','light favicon'],['docusaurus.config.js','favicon-white.svg','dark favicon'],['src/pages/index.jsx','Welcome,','personalised landing'],['src/pages/index.jsx','IdrWorkspace','interactive workspace'],['docs/12-week-sprint.md','| 12 | Executive presentation','week 12 table row'],['docs/credentials.md','Enterprise Design Thinking','credential targets'],['docs/portfolio.md','Project 5','five portfolio projects'],['docs/kpis.md','Role transition','development goals'],['static/CNAME','fksmm.skunkworksacademy.com','CNAME'],['static/downloads/fernanda-idr-12-week-calendar.ics','BEGIN:VCALENDAR','calendar'],['.github/workflows/deploy-pages.yml','actions/upload-pages-artifact@v4','Pages artifact action']];
for(const [f,t,d] of checks)if(!read(f).includes(t))errors.push(`${f}: missing ${d}`);
const forbidden=['fernandasmmacias@hotmail.com'];for(const base of ['docs','src']){for(const file of walk(path.join(root,base))){if(!/\.(md|mdx|js|jsx|css)$/.test(file))continue;const c=fs.readFileSync(file,'utf8');for(const term of forbidden)if(c.includes(term))errors.push(`${path.relative(root,file)}: contains protected contact information`)}}
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)])}
if(errors.length){console.error('IDR site validation failed.');errors.forEach(e=>console.error('- '+e));process.exit(1)}console.log('IDR site validation passed.');
